language: python

sudo: false

addons:
    apt:
        packages:
            # See: https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu
            - autoconf
            - automake
            - build-essential
            - cmake
            - libass-dev
            - libfreetype6-dev
            - libjpeg-dev
            - libtheora-dev
            - libtool
            - libvorbis-dev
            - libx264-dev
            - mercurial
            - pkg-config
            - texinfo
            - wget
            - yasm
            - zlib1g-dev
    homebrew:
        packages:
            - automake
            - libass
            - libjpeg
            - libpng
            - libtool
            - libvorbis
            - libvpx
            - nasm
            - opus
            - shtool
            - texi2html
            - theora
            - wget
            - x264

cache:
    directories:
        - tests/assets # Cache files from the FATE suite.
        - vendor/build/$LIBRARY # FFmpeg builds.
        - venvs/$TRAVIS_OS_NAME.$TRAVIS_PYTHON_VERSION # Python packages.

matrix:

    # There seems to be a bug in Travis that results in Mike getting piles of
    # emails as the sub-jobs finish when `fast_finish` is enabled.
    #fast_finish: true

    include:

        # Our primary targets are:
        # - Python 3.6 and 2.7;
        # - FFmpeg 4.1, 4.0, 3.4, 3.3, and 3.2 (i.e. major versions > 3.0 on the
        #   FFmpeg download page).

        # Source linting.
        - python: "3.6"
          env: TESTSUITE=flake8
        - python: "3.6"
          env: TESTSUITE=isort

        # Source distribution.
        - python: "3.6"
          env: TESTSUITE=sdist

        # Python 3.6.
        - python: "3.6"
          env: LIBRARY=ffmpeg-4.1
          os: linux
        - python: "3.6"
          env: LIBRARY=ffmpeg-4.0
          os: linux
        - python: "3.6"
          env: LIBRARY=ffmpeg-3.4
          os: linux
        - python: "3.6"
          env: LIBRARY=ffmpeg-3.3
          os: linux
        - python: "3.6"
          env: LIBRARY=ffmpeg-3.2
          os: linux

        # Python 2.7.
        - python: "2.7"
          env: LIBRARY=ffmpeg-4.1
          os: linux
        - python: "2.7"
          env: LIBRARY=ffmpeg-4.0
          os: linux
        - python: "2.7"
          env: LIBRARY=ffmpeg-3.4
          os: linux
        - python: "2.7"
          env: LIBRARY=ffmpeg-3.3
          os: linux
        - python: "2.7"
          env: LIBRARY=ffmpeg-3.2
          os: linux

        # Mac OS X (python3.6)
        - language: generic
          env: LIBRARY=ffmpeg-4.1
          os: osx
        - language: generic
          env: LIBRARY=ffmpeg-4.0
          os: osx
        - language: generic
          env: LIBRARY=ffmpeg-3.4
          os: osx
        - language: generic
          env: LIBRARY=ffmpeg-3.3
          os: osx
        - language: generic
          env: LIBRARY=ffmpeg-3.2
          os: osx

        # PyPy
        - python: "pypy"
          dist: xenial
          env: LIBRARY=ffmpeg-4.0
          os: linux
        - python: "pypy3"
          dist: xenial
          env: LIBRARY=ffmpeg-4.0
          os: linux

        # Newer Python 3.
        - python: "3.7"
          # Must force Ubuntu 16.04 LTS.
          # By default Travis is running 14.04.
          dist: xenial
          sudo: true
          env: LIBRARY=ffmpeg-4.0
          os: linux

        # Older Python 3.
        - python: "3.5"
          env: LIBRARY=ffmpeg-4.0
          os: linux
        - python: "3.4"
          env: LIBRARY=ffmpeg-4.0
          os: linux

    allow_failures:

        - python: "pypy3"
          dist: xenial
          env: LIBRARY=ffmpeg-4.0
          os: linux

before_install:
    - scripts/build-deps

install:
    - scripts/build

script:
    - scripts/test
