language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

env:
    - LD_LIBRARY_PATH=/usr/local/lib LIBRARY=ffmpeg LIBRARY_VERSION=2.7
    - LD_LIBRARY_PATH=/usr/local/lib LIBRARY=libav  LIBRARY_VERSION=11.4

before_install:
    - scripts/test-setup
    - pip install --use-mirrors -r tests/requirements.txt

install:
    - make build
    - make test-assets

script:
    - nosetests
