language: python

sudo: false

addons:
    apt:
        packages:
            # See: https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu
            - autoconf
            - automake
            - build-essential
            - cmake
            - libass-dev
            - libfreetype6-dev
            - libjpeg-dev
            - libtheora-dev
            - libtool
            - libvorbis-dev
            - libx264-dev
            - mercurial
            - pkg-config
            - texinfo
            - wget
            - yasm
            - zlib1g-dev

cache:
    directories:
        - tests/assets # Cache files from the FATE suite.
        - vendor/build/$LIBRARY # FFmpeg builds.
        - venvs/$TRAVIS_OS_NAME.$TRAVIS_PYTHON_VERSION # Python packages.

matrix:

    # There seems to be a bug in Travis that results in Mike getting piles of
    # emails as the sub-jobs finish when `fast_finish` is enabled.
    #fast_finish: true

    allow_failures:

        # PyPy doesn't pass recently, and I don't think it is our fault.
        - python: "pypy"
          env: LIBRARY=ffmpeg-3.2
          os: linux
        - python: "pypy3"
          env: LIBRARY=ffmpeg-3.2
          os: linux

        # We are still working on this.
        - os: osx

    include:

        # Primary targets.
        - python: "3.6"
          env: LIBRARY=ffmpeg-3.3
          os: linux
        - python: "2.7"
          env: LIBRARY=ffmpeg-3.3
          os: linux

        # Latest libraries.
        - python: "3.6"
          env: LIBRARY=ffmpeg-4.0
          os: linux
        - python: "3.6"
          env: LIBRARY=ffmpeg-3.4
          os: linux

        # Mac OS X.
        - env: LIBRARY=ffmpeg-3.2
          os: osx

        # PyPy
        - python: "pypy"
          env: LIBRARY=ffmpeg-3.2
          os: linux
        - python: "pypy3"
          env: LIBRARY=ffmpeg-3.2
          os: linux

        # Older Pythons.
        - python: "3.5"
          env: LIBRARY=ffmpeg-3.2
          os: linux
        - python: "3.4"
          env: LIBRARY=ffmpeg-3.2
          os: linux

        # Older libraries.
        - python: "2.7"
          env: LIBRARY=ffmpeg-3.2
          os: linux
        - python: "2.7"
          env: LIBRARY=ffmpeg-3.0
          os: linux



before_install:
    - scripts/travis-setup
    - scripts/build-deps

install:
    - scripts/build

script:
    - scripts/test
